#!/bin/sh

set -e

HERE=$(dirname $0)

rsync \
	--archive \
	--partial \
	--progress \
	--delete \
	--exclude .git \
	--exclude push \
	--delete-excluded \
	-- \
	$HERE quad_quadhome@ssh.phx.nearlyfreespeech.net:
