#!/bin/sh

set -e

FROM=$(dirname "$0")
TO=quad_quadsites@ssh.nyc1.nearlyfreespeech.net

rsync \
	--archive \
	--partial \
	--progress \
	--delete \
	--exclude "$(basename $0)" \
	--delete-excluded \
	--filter='dir-merge,e /.rsync-filter' \
	--filter 'protect .well-known' \
	--filter 'protect **/.well-known/acme-challenge' \
	$* \
	-- \
	"$FROM" "$TO:"

ssh "$TO" tls-setup.sh
